Repository CodyHarsh/Data-Structure-and-Algorithm-Qestion-and-Notes-in-cpp, pull requests merged in 2023-10, with the labels that each got.

#28 Create fibonacci.cpp
  Data Structures and Algorithm/Recursion 1/fibonacci.cpp
Labels: bug, hacktoberfest-accepted, hacktoberfest

#33 Create Rotate Array.cpp
  LeetCode/Rotate Array.cpp
Labels: bug, hacktoberfest-accepted, hacktoberfest

#32 Create Remove Duplicates from Sorted Array.cpp
  AtoZ Sheet Striver/Remove Duplicates from Sorted Array.cpp
Labels: hacktoberfest-accepted, hacktoberfest, easyfirst

#30 Create mcm.cpp
  LeetCode/mcm.cppt
Labels: hacktoberfest-accepted, hacktoberfest

#31 Create consicutive_number_in_array.cpp
  Data Structures and Algorithm/Recursion 2/Lecture/consicutive_number_in_array.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#39 Create Journey to the Moon.cpp
  LeetCode/Journey to the Moon.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#38 Create Game of Two Stacks.cpp
  LeetCode/Game of Two Stacks.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#36 Create Truck Tour.cpp
  LeetCode/Truck Tour.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#35 Create Queens on Board.cpp
  LeetCode/Queens on Board.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#48 1269. Number of Ways to Stay in the Same Place After Some Step…
  LeetCode/1269. Number of Ways to Stay in the Same Place After Some Steps.cpp
Labels: good first issue

#47 Create 779. K-th Symbol in Grammar.cpp
  LeetCode/779. K-th Symbol in Grammar.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#46 Create 823. Binary Trees With Factors
  LeetCode/823. Binary Trees With Factors
Labels: hacktoberfest-accepted, hacktoberfest

#45 Create 60. Permutation Sequence.cpp
  LeetCode/60. Permutation Sequence.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#44 Create 42. Trapping Rain Water.cpp
  LeetCode/42. Trapping Rain Water.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#43 Create Sudoku Solver.cpp
  LeetCode/Sudoku Solver.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#42 Create Regular Expression Matching.cpp
  LeetCode/Regular Expression Matching.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#41 Create 4Sum.cpp
  LeetCode/4Sum.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#51 Create String to Integer (atoi)
  LeetCode/String to Integer (atoi)
Labels: hacktoberfest-accepted, hacktoberfest

#52 Create Next Permutation
  LeetCode/Next Permutation
Labels: hacktoberfest-accepted, hacktoberfest

#50 Create Find the Index of the First Occurrence in a String
  LeetCode/Find the Index of the First Occurrence in a String
Labels: hacktoberfest-accepted, hacktoberfest

#49 Create Merge Two Sorted Lists
  LeetCode/Merge Two Sorted Lists
Labels: hacktoberfest-accepted, hacktoberfest
